version: "3.8"
services:
  traefik:
    image: "traefik:v2.5"
    container_name: "traefik"
    command:
      #- "--log.level=DEBUG"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:3000"
      - "--entrypoints.websecure.address=:8443"
      - "--certificatesresolvers.myresolver.acme.dnschallenge=true"
      - "--certificatesresolvers.myresolver.acme.dnschallenge.provider=cloudflare"
      - "--certificatesresolvers.myresolver.acme.email=yourmail@probablygmail.com"
      - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"
    environment:
      - "CF_DNS_API_TOKEN=KEY_WITH_DNS_WRITE"
      - "CF_ZONE_API_TOKEN=KEY_WITH_ZONE_READ"

    ports:
      - "3000:3000"
      - "443:443"
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - ./letsencrypt:/letsencrypt

  penny:
    build: ./path/to/penny/src
    command: serve --config /penny.yaml
    ports:
      - "3000"
    volumes:
      - ./config/penny.yaml:/penny.yaml
    depends_on:
      - mariadb
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.penny.rule=Host(`penny.domain.tld`)"
      - "traefik.http.routers.penny.entrypoints=websecure"
      - "traefik.http.routers.penny.tls.certresolver=myresolver"

  mariadb:
    image: "mariadb:10.5"
    ports:
      - "3306:3306"
    environment:
      MARIADB_ROOT_PASSWORD: RANDOMPASSWORDROOT
      MARIADB_DATABASE: penny
      MARIADB_USER: penny
      MARIADB_PASSWORD: RANDOMPASSWORD
    volumes:
      - ./db:/var/lib/mysql
